Streamz gQuant example
rapidsai/gQuant pull request #107
Opened 2020-10-12 21:32 UTC by yidong72

In this PR, it adds a dynamic gQuant nodes registration feature so the developer can build up a new set of gQuant nodes one by one. The node can be used properly in the client without server restart and browser refresh. It adds a cuStreamz gQuant example and updates the old 05_customize_nodes_with_ports notebook.

2020-10-12 21:33 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-19 23:17 UTC, avolkov1 requested changes
Please squash the commits.
```
git reset --soft a6b5d2c && git add -u && git commit --amend --no-edit

# you should now have just one commit after 6b7aa35
git rebase -i 6b7aa35

# choose reword and give that single commit some descriptive message.
# then: git push --force

```

After squashing the branch appeared like this for me:
```
commit da217bb560ce43598c174c772696cf067df845b5
Author: Yi Dong <yidong@nvidia.com>
Date:   Wed May 13 16:28:45 2020 -0700

    Add streamz examples
    
    Register gQuant Nodes dynamically with gQuantLab.

commit 6b7aa35faa2cb6916750a9fd22d4d315751bb85f
Author: yidong72 <43824965+yidong72@users.noreply.github.com>
Date:   Mon Oct 12 16:25:44 2020 -0400

    Nemo and xgboost integration  (#103)
    
    * Add NeMo and Cuml examples
    * clean up the dask client
    * Handle non-dask inputs for delayed dask processing.
    * Refactor NeMo gQuant nodes into a gquant plugin module.
.
.
.
```

I'll make a PR to fix the columns validation.

Thanks

2020-10-19 23:57 UTC, yidong72 commented
> Please squash the commits.
> 
> ```
> git reset --soft a6b5d2c && git add -u && git commit --amend --no-edit
> 
> # you should now have just one commit after 6b7aa35
> git rebase -i 6b7aa35
> 
> # choose reword and give that single commit some descriptive message.
> # then: git push --force
> ```
> 
> After squashing the branch appeared like this for me:
> 
> ```
> commit da217bb560ce43598c174c772696cf067df845b5
> Author: Yi Dong <yidong@nvidia.com>
> Date:   Wed May 13 16:28:45 2020 -0700
> 
>     Add streamz examples
>     
>     Register gQuant Nodes dynamically with gQuantLab.
> 
> commit 6b7aa35faa2cb6916750a9fd22d4d315751bb85f
> Author: yidong72 <43824965+yidong72@users.noreply.github.com>
> Date:   Mon Oct 12 16:25:44 2020 -0400
> 
>     Nemo and xgboost integration  (#103)
>     
>     * Add NeMo and Cuml examples
>     * clean up the dask client
>     * Handle non-dask inputs for delayed dask processing.
>     * Refactor NeMo gQuant nodes into a gquant plugin module.
> .
> .
> .
> ```
> 
> I'll make a PR to fix the columns validation.
> 
> Thanks

I squashed the commits using your commands.

2020-11-03 16:38 UTC, merged

2020-11-03 16:52 UTC, yidong72 commented on gquant/dataframe_flow/taskGraph.py
> +import cloudpickle
added it explicitly.

2020-11-03 19:13 UTC, yidong72 commented on notebooks/05_customize_nodes_with_ports.ipynb
> +    "Let's register the dynamically defined gQuant nodes so the client knows about them "
done

2020-11-03 19:13 UTC, yidong72 commented on notebooks/05_customize_nodes_with_ports.ipynb
> +    "task_graph.run(formated=True)"
removed

2020-11-03 19:18 UTC, yidong72 commented on gquant/dataframe_flow/taskGraph.py
fixed in the other PR